name: CI
on: [ push ]

jobs:
  tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            distribution: "adopt"
            java-version: 17
        - name: Eco CI Energy Estimation - Initialize
          uses: green-coding-berlin/eco-ci-energy-estimation@v2
          with:
              task: start-measurement
        - name: clean build
          run: ./gradlew clean test --info --stacktrace
        - name: Eco CI Energy Estimation - End Measurement
          uses: green-coding-berlin/eco-ci-energy-estimation@v2
          with:
            task: display-results
            branch: main
            pr-comment: true
        - name: Checkout Repo Measurment
          uses: green-coding-berlin/eco-ci-energy-estimation@v2
          id: checkout-step
          with:
            task: get-measurement
            label: 'repo checkout'
        - name: Print checkout data
          run: |
            echo "total json: ${{ steps.checkout-step.outputs.data-lap-json }}"
        - name: Print total data
          run: |
            echo "total json: ${{ steps.total-measurement-step.outputs.data-total-json }}"  
